bluecherrydvr/bluecherry-apps

docs/client.rst
Remove duplicated text and fix some punctuation
=> Minor doc update

www/ajax/webhook.php, www/lib/lang.php, www/lib/mailer.php, www/template/ajax/webhook.php
I added a trigger for solo event and additional fields datetime and dvr_name
=> additional solo event and datetime field

.gitignore, www/ajax/general.php, www/composer.json, www/index.php, www/lib/lang.php, www/lib/mailer.php, www/template/ajax/general.php
- Enhanced mail notification settings UI
- Obsolete pear mail library dependency replaced to swiftmailer library
Resolves #395
=> Mail Notification Settings UI & Mail Sender Library Upgrade

www/ajax/backup.php, www/template/ajax/backup.php
=> Resolve issue in web UI where database backup (and restore) fails

misc/sql/initial_data_mysql.sql, www/lib/Helpers.php, www/lib/lib.php, www/template/ajax/playback/index.php
=> 3.0.5 testing

server/motion_processor.cpp, server/motion_processor.h
Fixed bug: https://github.com/bluecherrydvr/bluecherry-apps/issues/425
=> Fixed segment violation bug during switch recording schedule

misc/postinstall.sh, nginx-configs/buster.conf, nginx-configs/php/bionic.conf, nginx-configs/php/bullseye.conf, nginx-configs/php/buster.conf, nginx-configs/php/focal.conf, nginx-configs/php/groovy.conf
Merge last changes from Nginx branch
=> Nginx latest changes

debian/bluecherry.conf.in, misc/sql/initial_data_mysql.sql, server/v3license_processor.cpp, server/v3license_server.cpp, www/ajax/licenses.php, www/ajax/subdomainprovider.php, www/ajax/subdomainproviderbase.php, www/lib/bc_license_wrapper.php, www/lib/lang.php, www/lib/lib.php, www/template/ajax/general.php, www/template/ajax/licenses.php, www/template/dist/css/main.css
I have completed the subdomain feature.
=> V3 licensing

misc/sql/initial_data_mysql.sql, server/bc-server.cpp, server/v3license_processor.cpp, server/v3license_processor.h, server/v3license_server.cpp, server/v3license_server.h, www/ajax/licenses.php, www/ajax/subdomainprovider.php, www/ajax/subdomainproviderbase.php, www/ajax/subdomainproviderquery.php, www/lib/bc_license_wrapper.php, www/lib/lang.php, www/lib/var.php, www/template/ajax/licenses.php, www/template/ajax/subdomainprovider.php, www/template/dist/js/licensing.js, www/template/dist/js/subdomainprovider.js, www/template/main_admin.php
I fixed some issues of subdomain and license features.
=>  V3 licensing

server/v3license_processor.cpp, www/lib/lib.php
Fixes: https://github.com/bluecherrydvr/bluecherry-apps/issues/475
=> Unlimited cameras for trial license

www/ajax/subdomainprovider.php
This reverts commit 863c8f1e7fcacbc779152262d7dba286f3a276b2.
=> Revert "Displaying new IPV4 of server"

misc/postinstall.sh
=> Don't overwrite nginx config for subdomain.conf if it exists

scripts/install_prereqs_native.sh
I've fixed the build error of v3.1.0-rc5. (issue #535)
=> Fixed the build error of v3.1.0-rc5.

server/v3license_processor.cpp, server/v3license_server.cpp, server/v3license_server.h
=> Fixed one issue of v3 license module

installer/v3.sh
Updated code that was stored off of GitHub
=> Rename install-unstable to v3.sh

misc/sql/mysql-upgrade/3000012/enlarge_devices_model_field.sh
See https://github.com/bluecherrydvr/bluecherry-apps/issues/647
=> Grow Devices.model DB field from 30 to 64 chars

debian/control.in, misc/onvif/discovery_json/node-onvif.js, misc/onvif/discovery_json/onvif_tool, scripts/build_helper/post_make_install.sh, www/ajax/discoverCameras.php
Transform output of different tools into the same simple minimal JSON format. We will be merging results of different tools for incremental presentation to the user.
=> ONVIF: combine findings of different discovery tools

debian/changelog
=> Prepare release v3.1.2

installer/v3.sh
* fix Ubuntu 24.04 (Noble)
* drop "-unstable" from source.list URL
* cleanup
=> Installer fixes

debian/bluecherry.logrotate, debian/control.in
See https://github.com/bluecherrydvr/bluecherry-apps/issues/596
=> Fix log rotation

scripts/check_dir_permission.sh, www/template/ajax/storage.php, www/template/main_viewer.php
Added sanitisation to text outputs where XSS was possible in response to a report
=> Vulnerability Patch

actions/Dockerfile
add  libcurl4-openssl-dev to the first section of apt-install
=> Update Dockerfile (add libcurl...again)

www/template/ajax/general.php
Fixes / Closes #728 
https://forums.bluecherrydvr.com/t/dvr-general-settings-page-is-missing-smtp-server-configuration/979/1
=> Do not crash if MAX_STORAGE_AGE is empty
