server/trigger_server.cpp
This will also prevent a buffer overread if an unusually long trigger
string is supplied.
=> Fix lack of string etiquette in the trigger server

www/lib/mailer.php
Currently a webhook fires for both a continuous recording and an actual motion event. Query the camera event and verify its type is `motion` before firing.
I have spun up a small webserver that dumps whatever requests it gets from the webhook and am able to validate I now only see motion events and not constant continuous recording rollovers. I didn't find any test suite to add to for this. I'll be monitoring this change in my own setup here for the next few days.
I realize I am coming into this pretty blind, but I think a better place to check this might be here: https://github.com/bluecherrydvr/bluecherry-apps/blob/abfd9979f1ff822442790a8428670921beaf18f3/server/recorder.cpp#L168
However I'm not able to easily build the C++ portion of Bluecherry because I run Fedora :grimacing:. I see …
=> Check motion event type before firing webhook

misc/sql/mysql-upgrade/3000010/increase_media_size_max.sh, misc/sql/schema_mysql.sql
Make `Media.size` a bigint rather than an INT. Fixes SQL "value out of range" errors that you start to see when setting continuous recording segment length to 1 hour or more.
I'm not sure. I didn't find a way to run these migrations, someone advise?
=> Increase Media.size limit to fix SQL errors

www/template/ajax/webhook.php, www/template/dist/js/webhook.js
This PR fixes an issue where webhook delete buttons are referred to in JavaScript code by its ID, which causes an issue (at least with Firefox) in that when there are multiple webhooks configured, the webhook test and delete buttons doesn't function correctly.
=> Webhook UI fix: test/delete button

misc/BCMK
Some video sources with AAC audio exhibit this persisten error: "Error writing frame to recording: Bitstream filter not found". MP4 muxer uses this bitstream filter to write AAC.
=> Add aac_adtstoasc bitstream filter to bundled ffmpeg configuration

misc/postinstall.sh
This is to get it upgraded from a pre-2.7.0 version which exhibits a bug https://github.com/bluecherrydvr/bluecherry-apps/issues/629
=> Make sure pip-installed certbot gets upgraded on bluecherry package update

installer/v3.sh
- Install wget to not fail when it's not there
- enable bash strict mode, so that errors are immediately visible
- annotate distro releases fully with families, codenames and numbers everywhere, because codenames are too much to remember, and mistakes in this are bad.
Installation with these changes was tested on all supported distros. Results:
* debian 10 good
* debian 11 glitched out, restarted and running good now
* mint vera good
* ubuntu 18.04 good
* ubuntu 20.04 good
* ubuntu 22.04 good
=> Sudo-bash-packages script improvements

misc/sql/schema_mysql.sql
This change complements commit 26ce91bdfe039f1ab7466cabada6002c07be6b2b . See https://github.com/bluecherrydvr/bluecherry-apps/issues/647
=> Grow Devices.model DB field to 64 chars (fixup)

lib/lavf_device.cpp, lib/lavf_device.h
This changes the behaviour of "Protocol" option of device configuration, which affects how the source RTSP stream is being consumed.
Historically, TCP was preferred.
Then, since
01bac09d5caf ("Refactored input device and added option to select AUTO rtp protocol") UDP with fallback to TCP became the default ("AUTO" mode). This makes picture in recordings prone to smearing, so it was decided to switch back to TCP by default.
Previously, fallback to TCP was done in our code; this commit makes use of FFmpeg's "rtsp_flags=+prefer_tcp" which accomplishes suitable behaviour: try TCP, fallback to UDP.
=> Prefer TCP again

misc/sql/mysql-upgrade/3000011/ip_manufacturer_lookup.sh
Quotes around literal strings disappeared at shell level, making MySQL think they are expressions.
Changed the outer quoting to double quotes and dropped the backticks around the table name.
=> mysql-upgrade: fix 3000011

www/ajax/discoverCameras.php
In bluecherry-node-onvif package, we bundle the dependencies necessary to avoid relying on packaging of all of them the Debian way.
The command "node .../discovery_json/node-onvif.js" doesn't work as it doesn't look for node_modules where we put them,
/usr/share/nodejs/onvif/node_modules .
This change passes NODE_PATH env var to `node` interpreter command, which is handled as expected by PHP's popen().
=> www/ajax/discoverCameras.php: set NODE_PATH for js tool cmd

misc/onvif/getRtspUrls.js, www/ajax/addip.php, www/ajax/discoverCameras.php
See https://github.com/bluecherrydvr/bluecherry-apps/issues/664
=> Use node.js ONVIF tool for getting RTSP URLs

installer/v3.sh
"mysql-server" package is not found in central Debian repos. We don't actually enable mysql.com repo, and we don't even want that, per https://github.com/bluecherrydvr/bluecherry-apps/issues/423 .
"default-mysql-server" package on Debian 10 installs mariadb-server-10.3.
=> installer: fix mysql server installation for Debian 10

www/template/dist/js/main.js
The issue outlined by #654 is caused when the client disconnects from the internet and can no longer send a request to `/ajax/stats.php`. The code that causes this is a commit made to solve issue #474 which sends the entire browser to the URL `/ajax/stats.php/` because the background request failed. 
The solution proposed by this PR works around both of these issues by create a way to create exception to the redirection when the request fails by simply passing false to the optional parameter `redirectOnFail`. 
This is by no means a proper solutions and a better solution for both issue #654 and #474 might be needed to be discussed.
=> Bug/654 redirect to stats.php on disconnect

www/ajax/editip.php, www/ajax/ipcameracheck.php, www/lib/lang.php, www/lib/lib.php, www/template/ajax/editip.php, www/template/dist/js/editip.js, www/template/main_admin.php
Issue #645 requests that a feature be added to the Web UI that allows the end user to test and preview the connection status the their devices in an effort to make it more obvious when authentication settings and paths are not correct. 
This PR contains changes to the `editip` stack (`/templates/ajax/editip.php`, `/templates/dist/js/editip.js`, `/ajax/editip.php`) and the function already contained within `lib.php` titled `checkConnection()`. 
This function previously incorrectly made a request for the header data of http URLs and assumed a 200 code would mean that the authentication succeeded. This was not the case. These have been substituted for an `ffprobe` command with a timeout of 5 seconds.
=> Feature/645 Test devices authentication

www/lib/VarPub.php
PHP Warning:  The magic method VarPub::__wakeup() must have public visibility in www/lib/VarPub.php on line 10
Found by
for x in $(find * -name '*.php' | grep -v /vendor/); do php -l $x; done
=> www: fix warning about magic method visibility

server/bc-server.cpp
Before, if there was any storage location below max use threshold, the cleanup was skipped. This might cause problem described in https://github.com/bluecherrydvr/bluecherry-apps/issues/656 : as long as one location has space, others might fill up if used by other processes. The default location, /var/lib/bluecherry/recordings/ is usually on the system rootfs, where many services' and users' activities contribute to increasing the filesystem space used.
Now, the media cleanup happens if any of the storage locations is over the threshold.
=> Change from lazy media storage cleanup to eager

debian/rules
Previously, the debug symbols were discarded by our building environment.
With this change, bluecherry-dbg packages again contain the debug symbols stripped from the built code.
Alternatively, we could change this code to "dh_strip --keep-debug" which adds 7 MB to bluecherry.deb, taking it from 28M to 35M.
The situation with instant access to crash backtraces enriched with debug symbols is now the following: the stack trace logged by bc-server itself lists the libraries for every stack frame, but not function names or line nubmers. This info is in the debug info shipped, but it is not used by glibc's backtrace() (wouldn't even if we avoid stripping overall).
The ways to use all the debug info are:
```sh
sudo -u bluecherry gdb -ex run -ex bt --args /usr/sbin/bc-server -s
```
```sh
sudo -u …
```
=> Put stripped debug symbols back into bluecherry-dbg

misc/postinstall.sh
postinstall.sh fails for Debian systems if /var/run/bluecherry doesn't exist.
For unclear reasons it sometimes doesn't exist.
See https://forums.bluecherrydvr.com/t/installation-error-on-var-run-bluecherry/891
=> Create /var/run/bluecherry in postinstall.sh

www/lib/lib.php
What happens: submit a form for creation of a new user, get a blank page.
Seen on Debian 12.
Apparently older versions of PHP were forgiving in this case.
```
==> /var/log/nginx/bluecherry-error.log <==
2024/08/31 23:01:42 [error] 380#380: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Non-static method user::checkUserData() cannot be called statically in /usr/share/bluecherry/www/lib/lib.php:459
Stack trace:
#0 /usr/share/bluecherry/www/ajax/update.php(54): user::update()
#1 /usr/share/bluecherry/www/ajax/update.php(30): update->newUser()
#2 /usr/share/bluecherry/www/lib/Controller.php(124): update->postData()
#3 /usr/share/bluecherry/www/lib/Route.php(75): Controller->start()
#4 /usr/share/bluecherry/www/index.php(16): Route->start()
#5 {main}
thrown in …
```
=> Fix error in user management web UI

www/lib/lib.php
"stimeout" option has been renamed into "timeout".
The bug broke the "Test connection to IP Camera" button in web UI.
=> Update option name following the ffmpeg upgrade

debian/bluecherry.service, misc/BCMK, server/media_writer.cpp, server/motion_processor.cpp, server/streaming.cpp
From repeated automated testing (1 stream on continuous+motion) I conclude that these changes bring down total leakage from 100+ KB/s to 1KB/s.
=> Memleaks fixes

server/media_writer.cpp
media_writer::scale_frame() converts the frame to a JPEG-compatible pixel format, but it doesn't carry over all the frame metadata like format, and picture dimensions. This is the apparent reason why video snapshots don't work. This problem has been reported by many users after the 3.1.2 release, which brought the upgrade of bundled ffmpeg to 6.1.1 from 4.2.1.
This change has been tested.
The problem shows up in the log like this:
I(1/camera_name): Making a snapshot
E(1/camera_name): avcodec_send_frame: snapshot encoding failed: Invalid argument
E(1/camera_name): failed to write snapshot frame
E(1/camera_name): Feeding snapshot decoder failed
E(1/camera_name): Failed to make snapshot
=> Fix video snapshots saving

server/media_writer.cpp, server/media_writer.h
The user-visible effect is that the recordings stick to the prescribed duration rather than randomly cut short.
The problem was that bad timestamps (situation which also occurs when just using ffmpeg) were attempted to be handled gracefully but were not done exactly right.
=> Make continuous recording handle bad timestamps gracefully

www/ajax/events/eventsIndex.php
We don't use media_duration, we use video_duration!
PHP message: PHP Notice:  Undefined index: media_duration in /usr/share/bluecherry/www/ajax/events/eventsIndex.php on line 128
root@fvi-bcdvr1:/usr/share/bluecherry/www/ajax/events# grep "media_duration" /var/log/nginx/bluecherry-error.log |wc -l 243107
=> Prevent media_duration warnings and null values from events API

server/media_writer.cpp
Specifically:
- Restart recording on timestamping problems
- Reset last_mux_dts[] on media_writer::close()
- consistently use AV_NOPTS_VALUE as "NULL" for last_mux_dts
- don't update last_mux_dts to a bad one which isn't muxed
Reliability regressions were reported on certain setups attributed to changes in 3.1.2 and 3.1.6.
One scenario in which problems arise is: an HDMI-to-RTSP encoder is connected as a device to Bluecherry server, and the upstream video source connected to the encoder is switched off and later back on.
This commit solves the issues for the scenario which we reproduced in our lab.
=> Improve timestamps handling at recording muxing

lib/lavf_device.cpp
In 3.1.2 release of Bluecherry server, we have upgraded bundled FFmpeg from 4.2.1 to 6.1.1. (Later, in 3.1.3, we upgraded to FFmpeg 6.1.2.)
Between 4.2.1 and 6.1.1, FFmpeg's RTSP demuxer has changed a parameter name from "stimeout" to "timeout", but we haven't updated lib/lavf_device.cpp accordingly. This causes the cameras on which RTSP connection broke to stop working until Bluecherry server is restarted or the camera is reconfigured in the database. We have received many such complaints from the users.
Link: https://github.com/bluecherrydvr/bluecherry-apps/issues/723
=> Fix hangs of RTSP connections to cameras

lib/BCMK, lib/bc-stats.cpp, lib/stream_elements.cpp, lib/stream_elements.h, server/BCMK, server/bc-api.cpp, server/bc-server.cpp, server/bc-thread.cpp, server/hls.cpp, server/motion_handler.cpp, server/motion_processor.cpp, server/recorder.cpp, server/rtsp.cpp, server/status_server.cpp, server/substream-thread.cpp, server/substream-thread.h, server/trigger_server.cpp, server/v3license_server.cpp
With this change, we can see the purpose of each threads in the debugger, like that:
```
(gdb) info threads
Id   Target Id                                      Frame
* 1    Thread 0x7f8ad6aef600 (LWP 3697) "MAIN"        0x00007f8ae02a5adf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7ffebcd3d9d0, rem=rem@entry=0x7ffebcd3d9d0)
at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
2    Thread 0x7f8acc8da6c0 (LWP 3737) "rcn2"        0x00007f8ae0251d71 in __futex_abstimed_wait_common64 (private=32650, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f8ac0057680)
at ./nptl/futex-internal.c:57
3    Thread 0x7f8acdffb6c0 (LWP 3730) "dev2"        0x00007f8ae02d44cd in __GI___poll (fds=fds@entry=0x7f8acdfeeda0, nfds=nfds@entry=1, …
```
=> Set thread names

www/ajax/devices.php
Should resolve this - https://github.com/bluecherrydvr/unity/issues/258
Add oldest_recording to XML and JSON, if NULL is returned add that to the tag
{
"id": "18",
"device_name": "DVD Player",
"protocol": "IP-RTSP",
"resolutionX": "640",
"resolutionY": "480",
"oldest_recording": "2025-03-14T16:29:08+00:00"
}
<device id="18">
<device_name>DVD Player</device_name>
<protocol>IP-RTSP</protocol>
<resolutionX>640</resolutionX>
<resolutionY>480</resolutionY>
<oldest_recording>2025-03-14T16:29:08+00:00</oldest_recording> </device>
=> Add support for oldest_recording
